### ISSUE TITLE
В случае добавления комментария на вашу фотографию создавать извещение

### ISSUE THREAD

**Issue by pingnome** [pavlov-dmitry/photometer#33]
В случае добавления комментария на вашу фотографию создавать извещение которое должно отобразиться на главной странице в не прочитанных, в случае если комментарий был прочтен то сообщение должно помечаться как прочитанное

**Comment by pavlov-dmitry** [comment]
Сделать оповещение не сложно. А вот автоматически его помечать как прочитанное, если ты сам случайно прочитал комментарий, уже сложнее. Может можно удовлетвориться пока без этой "функции" ?

**Comment by pingnome** [comment]
Давай сделаем так, если сообщение отобразилось в окне браузера, то считаем что сообщение было прочитано.

**Comment by pavlov-dmitry** [comment]
@pingnome Давай не так, давай, если пользователь нажал на ссылку внутри письма, то считаем, что он его прочел.
